// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class AccountList
{
    public ulong Id { get; set; }

    public string AccountName { get; set; }

    public double InitialBalance { get; set; }

    public string AccountNumber { get; set; }

    public string BranchCode { get; set; }

    public string BankBranch { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}