// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class AttendanceEmployee
{
    public ulong Id { get; set; }

    public int EmployeeId { get; set; }

    public DateOnly Date { get; set; }

    public string Status { get; set; }

    public TimeOnly ClockIn { get; set; }

    public TimeOnly ClockOut { get; set; }

    public TimeOnly Late { get; set; }

    public TimeOnly EarlyLeaving { get; set; }

    public TimeOnly Overtime { get; set; }

    public TimeOnly TotalRest { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Location { get; set; }

    public string TotalWork { get; set; }
}