// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class AttendanceRegularization
{
    public ulong Id { get; set; }

    public ulong AttendanceEmployeeId { get; set; }

    public ulong EmployeeId { get; set; }

    public ulong ManagerId { get; set; }

    public TimeOnly? ClockInTime { get; set; }

    public TimeOnly? ClockOutTime { get; set; }

    public DateOnly AttendanceDate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}