// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class ChMessage
{
    public long Id { get; set; }

    public string Type { get; set; }

    public long FromId { get; set; }

    public long ToId { get; set; }

    public string Body { get; set; }

    public string Attachment { get; set; }

    public bool Seen { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}