// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class CompanyPolicy
{
    public ulong Id { get; set; }

    public int Branch { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Attachment { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}