// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class ContractAttechment
{
    public ulong Id { get; set; }

    public ulong ContractId { get; set; }

    public string UserId { get; set; }

    public string Files { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}