// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Coupon
{
    public ulong Id { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public double Discount { get; set; }

    public int Limit { get; set; }

    public string Description { get; set; }

    public int IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}