// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Deposit
{
    public ulong Id { get; set; }

    public int AccountId { get; set; }

    public double Amount { get; set; }

    public DateOnly Date { get; set; }

    public int IncomeCategoryId { get; set; }

    public int PayerId { get; set; }

    public int PaymentTypeId { get; set; }

    public string ReferalId { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}