// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class GoalTracking
{
    public ulong Id { get; set; }

    public int Branch { get; set; }

    public int GoalType { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Subject { get; set; }

    public string Rating { get; set; }

    public string TargetAchievement { get; set; }

    public string Description { get; set; }

    public int Status { get; set; }

    public int Progress { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}