// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class JobOnBoard
{
    public ulong Id { get; set; }

    public int Application { get; set; }

    public DateOnly? JoiningDate { get; set; }

    public string Status { get; set; }

    public string JobType { get; set; }

    public int? DaysOfWeek { get; set; }

    public double? Salary { get; set; }

    public string SalaryType { get; set; }

    public string SalaryDuration { get; set; }

    public int ConvertToEmployee { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}