// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class LandingPageSection
{
    public ulong Id { get; set; }

    public string SectionName { get; set; }

    public int SectionOrder { get; set; }

    public string Content { get; set; }

    public string SectionType { get; set; }

    public string DefaultContent { get; set; }

    public string SectionDemoImage { get; set; }

    public string SectionBladeFileName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}