// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class LeaveType
{
    public ulong Id { get; set; }

    public string EmployeeId { get; set; }

    public string Title { get; set; }

    public decimal? CarryForwardLeave { get; set; }

    public decimal? MonthLeave { get; set; }

    public decimal Days { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}