// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class LoginDetail
{
    public ulong Id { get; set; }

    public string UserId { get; set; }

    public string Ip { get; set; }

    public string Date { get; set; }

    public string Details { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}