// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Meeting
{
    public ulong Id { get; set; }

    public int BranchId { get; set; }

    public string DepartmentId { get; set; }

    public string EmployeeId { get; set; }

    public string Title { get; set; }

    public DateOnly Date { get; set; }

    public TimeOnly Time { get; set; }

    public string Note { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}