// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class ModelHasPermission
{
    public ulong PermissionId { get; set; }

    public string ModelType { get; set; }

    public ulong ModelId { get; set; }

    public virtual Permission Permission { get; set; }
}