// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class NotificationTemplateLang
{
    public ulong Id { get; set; }

    public int ParentId { get; set; }

    public string Lang { get; set; }

    public string Content { get; set; }

    public string Variables { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}