// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class PaySlip
{
    public ulong Id { get; set; }

    public int EmployeeId { get; set; }

    public double NetPayble { get; set; }

    public string SalaryMonth { get; set; }

    public int Status { get; set; }

    public double BasicSalary { get; set; }

    public string Allowance { get; set; }

    public string Commission { get; set; }

    public string Loan { get; set; }

    public string SaturationDeduction { get; set; }

    public string OtherPayment { get; set; }

    public string Overtime { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? LopDeduction { get; set; }

    public int? DaysInMonth { get; set; }

    public decimal? WorkingPaidDays { get; set; }

    public decimal? LopDays { get; set; }

    public decimal? PaidLeaveTaken { get; set; }

    public double GrossSalary { get; set; }

    public decimal? MarkedAttendanceHoliday { get; set; }

    public decimal? LeaveAvailable { get; set; }
}