// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Plan
{
    public ulong Id { get; set; }

    public string Name { get; set; }

    public decimal? Price { get; set; }

    public string Duration { get; set; }

    public int MaxUsers { get; set; }

    public int MaxEmployees { get; set; }

    public double StorageLimit { get; set; }

    public string EnableChatgpt { get; set; }

    public int Trial { get; set; }

    public string TrialDays { get; set; }

    public int IsDisable { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}