// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class ReferralSetting
{
    public ulong Id { get; set; }

    public int Percentage { get; set; }

    public int MinimumThresholdAmount { get; set; }

    public int IsEnable { get; set; }

    public string Guideline { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}