// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class SalaryBand
{
    public ulong Id { get; set; }

    public string Name { get; set; }

    public string CtcBand { get; set; }

    public string Allowances { get; set; }

    public string Deductions { get; set; }

    public ulong CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}