// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Ticket
{
    public ulong Id { get; set; }

    public string Title { get; set; }

    public int EmployeeId { get; set; }

    public string Priority { get; set; }

    public DateOnly EndDate { get; set; }

    public string Description { get; set; }

    public string Attachment { get; set; }

    public string TicketCode { get; set; }

    public int TicketCreated { get; set; }

    public int CreatedBy { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}