// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Training
{
    public ulong Id { get; set; }

    public int Branch { get; set; }

    public int TrainerOption { get; set; }

    public int TrainingType { get; set; }

    public int Trainer { get; set; }

    public double TrainingCost { get; set; }

    public int Employee { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Description { get; set; }

    public int Performance { get; set; }

    public int Status { get; set; }

    public string Remarks { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}