// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class Trainer
{
    public ulong Id { get; set; }

    public string Branch { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Contact { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Expertise { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}