// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyBridgeHRMS.Models;

public partial class User
{
    public ulong Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public DateTime? EmailVerifiedAt { get; set; }

    public string Password { get; set; }

    public string Type { get; set; }

    public string Avatar { get; set; }

    public string Lang { get; set; }

    public int? Plan { get; set; }

    public DateOnly? PlanExpireDate { get; set; }

    public int RequestedPlan { get; set; }

    public DateOnly? TrialExpireDate { get; set; }

    public int TrialPlan { get; set; }

    public int IsLoginEnable { get; set; }

    public double StorageLimit { get; set; }

    public DateTime? LastLogin { get; set; }

    public int IsActive { get; set; }

    public int ReferralCode { get; set; }

    public int UsedReferralCode { get; set; }

    public int CommissionAmount { get; set; }

    public bool ActiveStatus { get; set; }

    public int IsDisable { get; set; }

    public bool DarkMode { get; set; }

    public string MessengerColor { get; set; }

    public string CreatedBy { get; set; }

    public string RememberToken { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}